spring:
  datasource:
    url: jdbc:postgresql://localhost:61257/coupon
    username: october03
    password: 1q2w3e4r!@
    driver-class-name: org.postgresql.Driver

api:
  base-url: http://localhost:61999